#ifndef PROTOCOL_H
#define PROTOCOL_H

#define MAX_PIPE_PATH_LENGTH 40
#define MAX_LEVEL_DIR_PATH 256

enum {
  OP_CODE_CONNECT = 1,
  OP_CODE_DISCONNECT = 2,
  OP_CODE_PLAY = 3,
  OP_CODE_BOARD = 4,
};

#endif
